# Generated by Django 3.1.7 on 2021-03-18 13:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardinalLocation', models.CharField(choices=[('S', 'South'), ('N', 'North'), ('E', 'East'), ('W', 'West'), ('SE', 'South East'), ('SW', 'South West'), ('NE', 'North East'), ('NW', 'North West')], default='E', max_length=2)),
                ('type', models.CharField(choices=[('DL', 'Deluxe'), ('SD', 'Standard'), ('ST', 'Suite')], default='SD', max_length=2)),
                ('status', models.CharField(choices=[('BKD', 'Booked'), ('AVL', 'Available')], default='AVL', max_length=3)),
                ('number', models.IntegerField()),
                ('pricePerDay', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('floor', models.IntegerField()),
                ('pictures', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='room_pictures', to=settings.FILER_IMAGE_MODEL)),
            ],
        ),
    ]
