# Generated by Django 3.1.7 on 2021-03-30 04:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import reservations.util


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('status', models.CharField(choices=[('BKD', 'Booked'), ('AVL', 'Available'), ('MTC', 'Maintenance')], default='AVL', max_length=3)),
                ('floor', models.IntegerField()),
                ('cardinalLocation', models.CharField(choices=[('S', 'South'), ('N', 'North'), ('E', 'East'), ('W', 'West'), ('SE', 'South East'), ('SW', 'South West'), ('NE', 'North East'), ('NW', 'North West')], default='E', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.CreateModel(
            name='RoomPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='roomImages')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictured_room', to='reservations.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type', to='reservations.roomtype'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_guests', to='reservations.guest')),
                ('room', models.ForeignKey(null=True, on_delete=reservations.util.NULL_OR_PROTECT, related_name='booked_room', to='reservations.room')),
            ],
        ),
    ]
