# Generated by Django 3.1.7 on 2021-04-08 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='booked_guests', to='reservations.guest'),
        ),
    ]
