# Generated by Django 3.1.7 on 2021-03-18 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('reservations', '0002_auto_20210318_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='pictures',
        ),
        migrations.CreateModel(
            name='RoomPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='room_picture', to=settings.FILER_IMAGE_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room', to='reservations.room')),
            ],
        ),
    ]
