# Generated by Django 3.1.7 on 2021-03-18 16:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image
import reservations.util


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('reservations', '0003_auto_20210318_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
                ('rate', models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
            ],
        ),
        migrations.RemoveField(
            model_name='room',
            name='pricePerDay',
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('BKD', 'Booked'), ('AVL', 'Available'), ('MTC', 'Maintenance')], default='AVL', max_length=3),
        ),
        migrations.AlterField(
            model_name='roompicture',
            name='picture',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='picture', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='roompicture',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictured_room', to='reservations.room'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkInDate', models.DateField()),
                ('checkOutDate', models.DateField()),
                ('guests', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='booked_guests', to='reservations.guests')),
                ('room', models.ForeignKey(null=True, on_delete=reservations.util.NULL_OR_PROTECT, related_name='booked_room', to='reservations.room')),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_type', to='reservations.roomtype'),
        ),
    ]
